keywords: IT/Programming/Picture/Cosmetic/etc...
author: suyeon Park,devsy0617@gmail.com
description: chavi의 생활형 블로그
avatar: /images/heart.png

#twitter: Ben_wenbin
#rss: atom.xml
#weibo: ben0036
instagram: developer_sy

# Comment
duoshuo:
disqus: chavi-world
